### ISSUE TITLE
*.TEMPLATE nodes are copied rather than moved

### ISSUE THREAD

**Issue by santiagozky** [Netcentric/system-env-install-hook#15]
When using .TEMPLATE nodes. it seems that the node is copied with the .TEMPLATE removed rather than moving it as the documentation states.

I have a basic setup with a node in a path `/etc/socialconfig/srpc/defaultconfiguration.TEMPLATE` with a couple of variables. When installing it I see both a node `defaultconfiguration` and a `defaultconfiguration.TEMPLATE`. 

The documentation implies that the original .TEMPLATE node should not be there (emphasis mine):

> any nodes that end with .TEMPLATE will be **moved** to the same name without .TEMPLATE (e.g. /etc/path/to/configfile/com.example.MyService.config.TEMPLATE will be **moved** to /etc/path/to/configfile/com.example.MyService.config with the values replaced)

I reproduced this with version 1.2.2

**Comment by ghenzler** [comment]
so you will have both the `.TEMPLATE` node and the regular node in the repository (because it happens in the `INSTALLED` phase, https://github.com/Netcentric/system-env-install-hook/blob/a304a7c9b07418e4b1c440e7e9b108664ea5b254/apply-system-env-install-hook/src/main/java/biz/netcentric/aem/applysystemenvinstallhook/ApplySystemEnvInstallHook.java#L114). 

Having both nodes is the regular setup and does not harm (for OSGi configurations it's ignored, also nodes like `jcr:content.TEMPLATE` in replication agents don't harm. I will clarify the documentation to not mention `move` but to say `copy with replaced properties`

**Comment by santiagozky** [comment]
thank you @ghenzler
